# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Publish Package

on:
  release:
    types:
      - released

permissions:
  id-token: write
  contents: read

jobs:
  build:
    if: github.event.release.target_commitish == 'main'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js 24.x
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: |
          TAG="${{ github.event.release.tag_name }}"

          if [[ "$TAG" =~ ^v?[0-9]+\.[0-9]+\.[0-9]+-(alpha|beta)\.[0-9]+$ ]]; then
            npm publish --provenance --access public --tag "${BASH_REMATCH[1]}"
          else
            npm publish --provenance --access public
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
